config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  resources :tasks

  resources :agent_applications

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'pages#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/agent_application.rb
class AgentApplication < ActiveRecord::Base
  belongs_to :user
  validates_formatting_of :company_zip, using: :us_zip
  validates_formatting_of :payment_zip, using: :us_zip
  validates_formatting_of :company_phone, using: :us_phone
  validates_formatting_of :agent_cell_phone, using: :us_phone
  validates_formatting_of :social_security, using: :ssn
  validates_formatting_of :company_fax, using: :us_phone
end

app/controllers/agent_applications_controller.rb
class AgentApplicationsController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_agent_application, only: [:show, :edit, :update, :destroy]

  # GET /agent_applications
  # GET /agent_applications.json
  def index
    @agent_applications = AgentApplication.all
  end

  # GET /agent_applications/1
  # GET /agent_applications/1.json
  def show
  end

  # GET /agent_applications/new
  def new
    @agent_application = AgentApplication.new
  end

  # GET /agent_applications/1/edit
  def edit
  end

  # POST /agent_applications
  # POST /agent_applications.json
  def create
    @agent_application = AgentApplication.new(agent_application_params)
    @agent_application.user = current_user

    respond_to do |format|
      if @agent_application.save
        format.html { redirect_to @agent_application, notice: 'Agent application was successfully created.' }
        format.json { render :show, status: :created, location: @agent_application }
      else
        format.html { render :new }
        format.json { render json: @agent_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agent_applications/1
  # PATCH/PUT /agent_applications/1.json
  def update
    respond_to do |format|
      if @agent_application.update(agent_application_params)
        format.html { redirect_to @agent_application, notice: 'Agent application was successfully updated.' }
        format.json { render :show, status: :ok, location: @agent_application }
      else
        format.html { render :edit }
        format.json { render json: @agent_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agent_applications/1
  # DELETE /agent_applications/1.json
  def destroy
    @agent_application.destroy
    respond_to do |format|
      format.html { redirect_to agent_applications_url, notice: 'Agent application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agent_application
      @agent_application = AgentApplication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agent_application_params
      params.require(:agent_application).permit(:user_id, :status, :company_name, :company_address, :company_city, :company_zip, :company_state, :check_payable_to, :payment_address, :payment_city, :payment_zip, :company_phone, :agent_cell_phone, :social_security, :company_fax, :license_number, :license_expiration, :eo_policy_number, :eo_expiration)
    end
end

app/helpers/agent_applications_helper.rb
module AgentApplicationsHelper
end

app/views/agent_applications/_form.html.erb
<%= form_for @agent_application, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :status, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :status, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :company_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :company_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :company_address, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :company_address, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :company_city, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :company_city, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :company_zip, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :company_zip, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :company_state, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :company_state, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :check_payable_to, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :check_payable_to, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :payment_address, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :payment_address, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :payment_city, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :payment_city, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :payment_zip, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :payment_zip, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :company_phone, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :company_phone, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :agent_cell_phone, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :agent_cell_phone, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :social_security, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :social_security, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :company_fax, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :company_fax, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :license_number, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :license_number, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :license_expiration, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.date_select :license_expiration, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :eo_policy_number, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :eo_policy_number, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :eo_expiration, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.date_select :eo_expiration, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  agent_applications_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/agent_applications/edit.html.erb
<%- model_class = AgentApplication -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => AgentApplication %></h1>
</div>
<%= render :partial => 'form' %>

app/views/agent_applications/index.html.erb
<%- model_class = AgentApplication -%>
<div class="page-header">
  <h1><%=t '.title', :default => AgentApplication %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:company_name) %></th>
      <th><%= model_class.human_attribute_name(:company_address) %></th>
      <th><%= model_class.human_attribute_name(:company_city) %></th>
      <th><%= model_class.human_attribute_name(:company_zip) %></th>
      <th><%= model_class.human_attribute_name(:company_state) %></th>
      <th><%= model_class.human_attribute_name(:check_payable_to) %></th>
      <th><%= model_class.human_attribute_name(:payment_address) %></th>
      <th><%= model_class.human_attribute_name(:payment_city) %></th>
      <th><%= model_class.human_attribute_name(:payment_zip) %></th>
      <th><%= model_class.human_attribute_name(:company_phone) %></th>
      <th><%= model_class.human_attribute_name(:agent_cell_phone) %></th>
      <th><%= model_class.human_attribute_name(:social_security) %></th>
      <th><%= model_class.human_attribute_name(:company_fax) %></th>
      <th><%= model_class.human_attribute_name(:license_number) %></th>
      <th><%= model_class.human_attribute_name(:license_expiration) %></th>
      <th><%= model_class.human_attribute_name(:eo_policy_number) %></th>
      <th><%= model_class.human_attribute_name(:eo_expiration) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @agent_applications.each do |agent_application| %>
      <tr>
        <td><%= agent_application.id %></td>
        <td><%= agent_application.status %></td>
        <td><%= agent_application.company_name %></td>
        <td><%= agent_application.company_address %></td>
        <td><%= agent_application.company_city %></td>
        <td><%= agent_application.company_zip %></td>
        <td><%= agent_application.company_state %></td>
        <td><%= agent_application.check_payable_to %></td>
        <td><%= agent_application.payment_address %></td>
        <td><%= agent_application.payment_city %></td>
        <td><%= agent_application.payment_zip %></td>
        <td><%= agent_application.company_phone %></td>
        <td><%= agent_application.agent_cell_phone %></td>
        <td><%= agent_application.social_security %></td>
        <td><%= agent_application.company_fax %></td>
        <td><%= agent_application.license_number %></td>
        <td><%= agent_application.license_expiration %></td>
        <td><%= agent_application.eo_policy_number %></td>
        <td><%= agent_application.eo_expiration %></td>
        <td><%=l agent_application.created_at, format: :long %></td>
        <td>
          <%= link_to agent_application_path(agent_application), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to agent_application_path(agent_application), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_agent_application_path,
            :class => 'btn btn-primary' %>

app/views/agent_applications/new.html.erb
<%- model_class = AgentApplication -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => AgentApplication %></h1>
</div>
<%= render :partial => 'form' %>

app/views/agent_applications/show.html.erb
<%- model_class = AgentApplication -%>
<div class="page-header">
  <h1><%=t '.title', :default => AgentApplication %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:status) %></dt>
      <dd><pre class="prettyprint"><%= @agent_application.status %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:company_name) %></dt>
      <dd><pre class="prettyprint"><%= @agent_application.company_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:company_address) %></dt>
      <dd><pre class="prettyprint"><%= @agent_application.company_address %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:company_city) %></dt>
      <dd><pre class="prettyprint"><%= @agent_application.company_city %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:company_zip) %></dt>
      <dd><pre class="prettyprint"><%= @agent_application.company_zip %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:company_state) %></dt>
      <dd><pre class="prettyprint"><%= @agent_application.company_state %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:check_payable_to) %></dt>
      <dd><pre class="prettyprint"><%= @agent_application.check_payable_to %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:payment_address) %></dt>
      <dd><pre class="prettyprint"><%= @agent_application.payment_address %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:payment_city) %></dt>
      <dd><pre class="prettyprint"><%= @agent_application.payment_city %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:payment_zip) %></dt>
      <dd><pre class="prettyprint"><%= @agent_application.payment_zip %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:company_phone) %></dt>
      <dd><pre class="prettyprint"><%= @agent_application.company_phone %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:agent_cell_phone) %></dt>
      <dd><pre class="prettyprint"><%= @agent_application.agent_cell_phone %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:social_security) %></dt>
      <dd><pre class="prettyprint"><%= @agent_application.social_security %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:company_fax) %></dt>
      <dd><pre class="prettyprint"><%= @agent_application.company_fax %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:license_number) %></dt>
      <dd><pre class="prettyprint"><%= @agent_application.license_number %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:license_expiration) %></dt>
      <dd><pre class="prettyprint"><%= @agent_application.license_expiration %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:eo_policy_number) %></dt>
      <dd><pre class="prettyprint"><%= @agent_application.eo_policy_number %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:eo_expiration) %></dt>
      <dd><pre class="prettyprint"><%= @agent_application.eo_expiration %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              agent_applications_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_agent_application_path(@agent_application), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              agent_application_path(@agent_application),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>